on:
 # push:
    #branches: master
  workflow_dispatch
name: ci/cd

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: setup Java Environment
      uses: actions/setup-java@v2
      with:
         java-version: '11'
         distribution: 'adopt'      
           
    - name: Build Snapshots run Tests
      run: mvn --batch-mode --update-snapshots verify


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: 1.0
      run: |
        # Build a docker container and push it to ECR 
        docker build -f src/main/docker/Dockerfile -t $ECR_REGISTRY/test_code_repo:latest .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/test_code_repo:latest
        echo "::set-output name=image::$ECR_REGISTRY/test_code_repo:$IMAGE_TAG"
