name: ci/cd

on:
  push:
    branches:
    - 'master' # When a push event occurs on master this workflow runs
    
    # Allows you to run this workflow manually from the Actions tab
    #workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
      
            
       - name: Run a multi-line script
         run: |
          ls -la
          cd ./CodingTest-CDK/bin
          ls -la

