name: ci/cd

on:
  push:
    branches:
    - 'master' # When a push event occurs on master this workflow runs
    
    # Allows you to run this workflow manually from the Actions tab
    #workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: setup Java Environment
         uses: actions/setup-java@v2
         with:
           java-version: '11'
           distribution: 'adopt'      
           
         
       - name: Run a multi-line script
         run: |
          ls -la
          cd .
          ls -la
          
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.ECS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.ECS_SECRET_ACCESS_KEY }}
           aws-region: ap-southeast-2
          
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
         
       - name: Build, tag, and push the image to Amazon ECS
         
         run: |
           docker build -f src/main/docker/Dockerfile -t public.ecr.aws/z8u8r9w4/my_test_repo:latest .
           echo "Pushing image to ECR..."
           docker push public.ecr.aws/z8u8r9w4/my_test_repo:latest
            
