name: ci/cd

on:
  push:
    branches:
    - 'master' # When a push event occurs on master this workflow runs
    
    # Allows you to run this workflow manually from the Actions tab
    #workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: setup Java Environment
         uses: actions/setup-java@v2
         with:
           java-version: '11'
           distribution: 'adopt'      
           
         
       - name: Run a multi-line script
         run: |
          ls -la
          cd .
          ls -la

         
       - name: Docker Build
         run: docker build -f src/main/docker/Dockerfile -t adamcoppens/coding-test-app .
         
       - name: Push Docker to Image ECR Repo
         run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
            
       - name: Run a multi-line script
         run: |
          ls -la
          cd ../
          ls -la
          cd ../
          ls -la

