name: ci/cd

on:
  push:
    branches:
      - 'master' # When a push event occurs on master this workflow runs
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
        name: Build and push # Build docker file and push to our repo
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: 'src/main/docker/Dockerfile'
          push: true
          tags: adamcoppens/coding-test-app:latest
  aws_cdk: # Deploy our CDK Stack based on our cdk project files
    runs-on: ubuntu-latest
    
    steps:
    - 
     name: Checkout
     uses: actions/checkout@v2
     with:
       submodules: true
    - 
      name: cdk deploy 
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'aws-cdk-project'
        cdk_args: '--app'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
